### ISSUE TITLE
Example 1 could be improved

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/tcp-udp-sockets#25]
Example 1 in the spec would not do anything, afaict. Also, it contains some stylistic issues that could lead to bugs if copied (eg, relies on globals)

**Comment by marcoscaceres** [comment]
Actually, it would do stuff. Just got a bit confused as I assumed there would be an open() method. I'll clean up the example a bit and add a comment about it automatically opening

**Comment by ClaesNilsson** [comment]
Yes, there is no open() method as the opening process is initiatedn by the constructor. This semantics is similar to Web Sockets but I chosed to call the state resulting from the constrcutor "opening" instead of "connecting" as "connecting" would be wrong for UDP.

Could you state the changes you want to do with the example?
